apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrent
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
      - name: torrent
        image: 2devops3/torrent:v0.1
        ports:
        - containerPort: 3000
